{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
{{- with $job }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and (hasKey . "serviceAccount") (hasKey . "serviceAccount.name") }}
  name: {{ .serviceAccount.name }}
  {{- else }}
  name: {{ .name }}
  {{- end }}
  labels:
    app: {{ $release_name }}
    cron: {{ .name }}
  {{- if and (hasKey . "serviceAccount") (hasKey . "serviceAccount.annotations") }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
