{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "helm-microservice.fullname" . -}}
{{- $servicePort := .Values.ingress.servicePortOverride | default .Values.service.portName -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "helm-microservice.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if .Values.ingress.hackAnnotations }}
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.subDomain }}{{ .Values.ingress.baseDomain }}"
{{- end }}
  {{- if .Values.ingress.extraLabels }}
  labels:
    {{- include "helm-microservice.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{ $subDomain := .Values.ingress.subDomain | default "" }}
  rules:
  {{ $path := .Values.ingress.path }}
  {{- range .Values.ingress.hosts }}
    {{ $fullDomain := printf "%s%s" $subDomain . }}
    - host: {{ $fullDomain | quote }}
      http:
        paths:
          - path: {{ $path | quote }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{- if .Values.ingress.tlsSecretName.enabled }}
    - secretName: {{ .Values.ingress.tlsSecretName.name }}
{{- else }}
    - secretName: {{ template "helm-microservice.fullname" . }}-skael-ai-tls 
{{- end }}
      hosts:              
{{- range .Values.ingress.hosts }}
          {{ $fullDomain := printf "%s%s" $subDomain . }}
        - {{ $fullDomain | quote }}
{{- end }}
  {{- end -}}
{{- end -}}
