{{- $create_gcp := .Values.gcpcreds_file.create -}}
{{ if $create_gcp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-microservice.fullname" . }}-gcp-secrets
  labels:
    app: {{ template "helm-microservice.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  gcp-creds-file: {{ .Values.gcp_creds_file | b64enc | quote }}
{{ end }}
