{{- $create_gcp := .Values.gcpcreds_file.create -}}
{{ if $create_gcp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-microservice.fullname" . }}-gcp-secrets
  labels:
    {{- include "helm-microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "helm-microservice.annotations" . | nindent 4 }}
data:
  gcp-creds-file: {{ .Values.gcp_creds_file | b64enc | quote }}
{{ end }}
