apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-microservice.fullname" . }}
  labels:
    {{- include "helm-microservice.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.portName }}
{{- if .Values.service.additionalPorts.enabled }}
{{ toYaml .Values.service.additionalPorts.ports | indent 2 }}
{{- end }}
  selector:
    {{- include "helm-microservice.selectorLabels" . | nindent 4 }}
