{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "helm-microservice.labels" . | nindent 4 }}
  name: {{ .Values.serviceAccount.name | default (printf "%s" (include "helm-microservice.fullname" .)) }}
  annotations:
    {{- include "helm-microservice.annotations" . | nindent 4 }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end -}}
