{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "helm-microservice.fullname" . -}}
{{- $servicePort := .Values.service.portName -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm-microservice.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.ingress.extraLabels }}
  labels:
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  {{- $url := splitList "/" . }}
    - host: {{ first $url | quote }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
